### PR TITLE
Add arrow key hot-keys to XL3, SNOCrate, SNORack, FEC and DB view

### PR DESCRIPTION
**Pull request by marzece**
Haven't tested yet. Probably will have to test on the full detector.

### CODE REVIEW

**Comment by marzece** [comment]
I briefly tested this UG. I tried sending a command from each of the dialogues I added hot-keys to and made sure the command got sent to the correct board. Everything seemed to work as expected.

**Comment by tlatorre-uchicago** [comment]
Sweet! What are the cancelOperation functions for? I think it would also be good to add a bit more error checking. There seems to be a good example here: https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/EventOverview/HandlingKeyEvents/HandlingKeyEvents.html in Listing 5-4. Specifically, making sure that it has the right number of characters, ignoring modifier keys, and passing the keys onto the super class if it's not the key you're expecting.

**Comment by marzece** [comment]
I made each chunk of code look a bit more like the thing you pointed to.

The cacelOperation is so when someone hits the ESC key it removes focus from the input field. For a couple of views if you started entering a value there was no way to 'exit' the input dialog, so the hot keys didn't work.

**Comment by tlatorre-uchicago** [comment]
Looks like the crate view is different from the others, i.e. pressing h on crate view increases the crate number instead of decreasing it.

**Comment by marzece** [comment]
Oops, fixed.

**Comment by tlatorre-uchicago** [comment]
merged.

**Pull request closed without merging**
