### PR TITLE
SMELLIE

### PR DESCRIPTION
**Pull request by EdLeming**
Changes to allow stable SMELLIE running for the May FTB dark running.

### CODE REVIEW

**Comment by EdLeming** [comment]
@tlatorre-uchicago, this should be ready to go. There's a line in ORMJDDewarScaleModel that won't compile on 5.1.1, but I guess this is probably a known issue.

**Comment by marzece** [comment]
It looks like you'll need to make this work in the post force-push world that we're living in. The easiest way to do so (that I know of) is to squash all of your commits into a single commit (which is advised anyway) then from a branch that is current with snoplus master git cherry-pick that squashed commit. Then push that to github.

**Comment by tlatorre-uchicago** [comment]
Ed, did you fix this after testing last night and verify that it was fixed?

**Comment by EdLeming** [comment]
As far as I could tell the ellie code worked as expected last night.

I think the issues we saw derive from one of the links in the data stream
chain, which was being overloaded bye 1kHz of peds from a few thousand
channels

**Comment by tlatorre-uchicago** [comment]
I thought things went haywire? How do you know it was a data stream problem?

**Comment by tlatorre-uchicago** [comment]
Also, which part of the code is sending pedestals?

**Comment by tlatorre-uchicago** [comment]
Also, it appears that the builder was getting MTC trigger masks with all triggers masked in. This I don't think could be a data stream problem, unless there is a serious bug which is sending random bytes to the builder.

**Comment by EdLeming** [comment]
To start the builder spit out a load of orphans, then the GTID in xsnoed went crazy. In the end it was resolved by re-initing the xl3s. Maybe some buffers got overloaded somewhere. 

Currently smellie slave mode requests peds from the MTCD. Eventually this will be replaced by some communication with Tubii, but that is not finished yet

**Comment by EdLeming** [comment]
Yeah the code doesn't mask triggers in, they had just been all masked in for stability running by Ian. We didn't think to change them for the first run - which is when things went crazy. When we dropped to 5 crates (the ones to be used for SMELLIE) it settled down.

**Comment by EdLeming** [comment]
...sorry, I'm talking about masking crates in, not the trigger mask on the MTCD. That I have no idea about.

**Comment by tlatorre-uchicago** [comment]
So, did you update the code to only mask in the TUB and SMELLIE?

**Comment by EdLeming** [comment]
I don't mask in any triggers at all. That will have to be done by the operator.

**Comment by tlatorre-uchicago** [comment]
But don't you only want the pedestals to go to SMELLIE?

**Comment by EdLeming** [comment]
That's right, we just sent them to all the crates last night through operator error

**Comment by tlatorre-uchicago** [comment]
I think it would be nice to just code that in. If you start a SMELLIE run then it only masks in the TUB and SMELLIE and then resets the crate mask at the end of the run.

**Comment by EdLeming** [comment]
OK, I guess SMELLIE will be in one of the 'spare' slots shown on the mtc gui?

**Comment by tlatorre-uchicago** [comment]
merged.

**Pull request closed without merging**
