### PR TITLE
Added the wpxmlrpc library and the XmlrpcClient wrapper class for com…

### PR DESCRIPTION
**Pull request by EdLeming**
…munication with the tellie and smellie servers

I this could be seen as equivalent to the hiredis library and complementary RedisClient class made by Eric / Tony.

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
I just tried to compile this using XCode 5 and I'm getting three errors:

Expected ':' for lines 47, 58, and 70 in WPXMLRPCEncoder.h

To test compilation with XCode 5 you can download it from the Apple developer website.

**Comment by tlatorre-uchicago** [comment]
Note also that there are two lines in ORMJDDewarScaleModel that don't compile on XCode 5.0, but those aren't our problem (I fix them when compiling by just fixing them according to whatever XCode suggests).

**Comment by EdLeming** [comment]
Thanks for catching. I added a macro to resolve.

**Comment by tlatorre-uchicago** [comment]
merged.

**Pull request closed without merging**
