### PR TITLE
SNO: Try to solve SNO+ GUI crashes.

### PR DESCRIPTION
**Pull request by jcaravaca**
Author: Javier Caravaca <jcaravaca@berkeley.edu>

### CODE REVIEW

**Comment by jcaravaca** [comment]
This is an attempt to fix the SNO+ GUI crashes due to the standard runs selection.
This PR is against tag0.6 intended to be deployed on site. I'll rebase with master if the fix works and resubmit.

**Comment by tlatorre-uchicago** [comment]
In all three functions updated, there are early return statements which will leak memory.

**Comment by jcaravaca** [comment]
According to Mark Howe, early returns do not leak memory as long as the copies are matching a release statement.

**Comment by tlatorre-uchicago** [comment]
Huh? I'm not sure I understand. What do you mean by "the copies are matching a release statement"?

**Comment by jcaravaca** [comment]
Literally from Mark Howe:
> As long as the copies are paired with releases, even in the cases were an early return can happen that would not leak.

**Comment by tlatorre-uchicago** [comment]
I'm assuming he meant that you won't leak memory as long as you release before the early return.

**Comment by jcaravaca** [comment]
Hmm, that might make more sense. I was assuming some Coca magic here...

**Comment by tlatorre-uchicago** [comment]
Are you convinced that this has fixed the problem? If so, I can merge this later today and we can make a new release.

**Comment by jcaravaca** [comment]
Before the change it used to crash 1 out of 3 times we changed a run.
After the change on Saturday we haven't had any crash.

**Comment by tlatorre-uchicago** [comment]
merged.

**Pull request closed without merging**
