### PR TITLE
SNO+: Add Run Type Word Headers to be shared with the RAT code

### PR DESCRIPTION
**Pull request by jcaravaca**
Author: Javier Caravaca <jcaravaca@berkeley.edu>

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
I prefer the old style of defining the run types using the mask so that you can check the run type with a simple and statement:

```
if (run_type & DIAGNOSTIC_RUN)
```

This is how the run type is defined in XSNOED and all the daq code.

**Comment by jcaravaca** [comment]
@tlatorre-uchicago I can change that, but I'd prefer to keep the enum rather than the define statements that there were in the old version

**Comment by tlatorre-uchicago** [comment]
Sure, that sounds good.

**Comment by jcaravaca** [comment]
Just let me know if you are happy with the changes but **do not merge yet**. I have to wait for approval of the RAT CIC as well.

**Comment by jcaravaca** [comment]
CIC has merged this already into RAT so it should be ready to go now.

**Comment by tlatorre-uchicago** [comment]
merged.

**Pull request closed without merging**
