### PR TITLE
SNO+: Bug fixes.

### PR DESCRIPTION
**Pull request by jcaravaca**
Prevent crashes when SR type and version not correctly set. Stop running ORCA script when stopping runs.

PR by Javier Caravaca

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
@jcaravaca, can you remove the purely stylistic changes from this?

**Comment by jcaravaca** [comment]
@tlatorre-uchicago I rearranged few lines as I went to get the code more tidy and readable. It doesn't affect performance, is there any problem with keeping them?

**Comment by tlatorre-uchicago** [comment]
The two I have issue with is the detector tile one because that is going to cause a merge conflict and the debugdbtestaction since it no longer fits in 80 characters.

**Comment by tlatorre-uchicago** [comment]
merged.

**Pull request closed without merging**
