### PR TITLE
HV Control Updates

### PR DESCRIPTION
**Pull request by BenLand100**
This is awaiting additions to the XL3 status packet to get the init status of the XL3 so that HV controller can enter into a known state as soon as the XL3 connects.

### CODE REVIEW

**Comment by BenLand100** [comment]
Obviously will have to TIAS but this should be good to go.

**Comment by tlatorre-uchicago** [comment]
TIAS?

**Comment by BenLand100** [comment]
Try It And See - forgot to expand my acronyms.

**Comment by tlatorre-uchicago** [comment]
Ah OK! I thought it was "test it at site".

**Pull request closed without merging**
