### PR TITLE
SNO+: TUBii unit corrections.

### PR DESCRIPTION
**Pull request by icoulter**
SNO+: TUBii previously used ns for the delay lengths and s for the pulse widths which was confusing. This brings things into line and changes the gui to give ns as units for everything.

### CODE REVIEW

**Comment by icoulter** [comment]
This is purely a change to gui as the rest is dealt with in the firmware.
@EdLeming Can you point me at the ELLIE code that needs to changed along with this?

**Comment by EdLeming** [comment]
Hey @icoulter. Thanks for the heads up see below:

https://github.com/snoplus/orca/blob/master/Source/Objects/Custom%20Hardware/SNO%2B/ELLIE/ELLIEModel.m#L887

https://github.com/snoplus/orca/blob/master/Source/Objects/Custom%20Hardware/SNO%2B/ELLIE/ELLIEModel.m#L1858

Thanks!

**Comment by icoulter** [comment]
Thanks.

**Comment by tlatorre-uchicago** [comment]
Has this already been changed in the firmware?

**Comment by icoulter** [comment]
No, I was waiting for some LV to do it as I don't like changing firmware while at HV. It shouldn't be merged until the firmware is updated though, otherwise ELLIE won't work properly.
Its been tested locally.

**Comment by ecaden** [comment]
Can this be tested tomorrow then?

--
Erica Caden, Ph.D.
SNOLAB Research Scientist
SNO+ Detector Manager
ecaden@snolab.ca
+1.705.692.7000 x2253

**Comment by icoulter** [comment]
Perhaps in the afternoon. I need to wait in for a package in the morning.
It doesn't really need testing as it worked locally and is a very  
minor change. Just a firmware update.

Quoting ecaden <notifications@github.com>:

> Can this be tested tomorrow then?
>
> --
> Erica Caden, Ph.D.
> SNOLAB Research Scientist
> SNO+ Detector Manager
> ecaden@snolab.ca
> +1.705.692.7000 x2253
>

**Comment by icoulter** [comment]
New firmware has been loaded to the TUBii onsite.

**Comment by tlatorre-uchicago** [comment]
merged. Note: Now that this has changed in the firmware, we should *not* run ELLIE until the new Orca release is finished.

**Comment by icoulter** [comment]
Thanks.
Just as a comment, I don't think we can run ELLIE until the new release as it will send 5e-8 as the pulse width (expected it in seconds) which will effectively be 0 as the firmware works in nanoseconds now. In which case, it just won't do anything. So I think this mismatch is safe but you're right that we're probably best just not trying.

**Pull request closed without merging**
