### PR TITLE
SNO+: Gray out Standard Run popup menus

### LINKED ISSUE #484: Changing run in run type drop down while run is starting results in inconsitent run info
I was attempting to change the standard run values by switching into a physics run then quickly changing to a diagnostic run.  While ORCA was changin runs and the stoplight graphic was at yellow,  I changed the run selection drop down to select diagnostic. When the run actually started orca claimed the run type was diagnostic. But the run type word in the database for the run was physics. I was also able to change detector settings because orca though it was in a diagnostic run.

### PR DESCRIPTION
**Pull request by jcaravaca**
Attempt to fix #484

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
The fundamental problem here (which is maybe also responsible for #450 and #475) is that you have the display bound to lastStandardRunType, but this is not guaranteed to be the same as the standard run which was actually loaded to the detector because you set lastStandardRunType in the `runStarted` method which is *after* the settings were loaded.

So, I think it should be decided what exactly the `lastStandardRunType` variable should represent. If you want it to represent the last standard run that was loaded then it should be set in `loadStandardRun` (but note that this is not necessarily the same as actually running the run since you can load in a different standard run). If you want it to be the last standard run settings that were loaded at the start of a run, then it should go in `startStandardRun`, and finally, if you want it to be the last standard run that was *successfully* started, then you'll need a third variable like `pendingStandardRunType` or something which is set in `startStandardRun` and then `lastStandardRunType` is set to this variable when the run successfully starts.

**Comment by jcaravaca** [comment]
The definition is the third one: `lastStandardRunType` should be the last SR that successfully started. As I understand your proposal, it is equivalent than graying out the menu so that it's not possible to change the current `standardRunType`, right?. `pendingStandardRunType` would be equivalent to `standardRunType` in this case.

**Comment by tlatorre-uchicago** [comment]
Sort of. This fix would probably work in 99% of the cases, but the standardRunType is set programatically (so it's not true that the only way to change it is through the GUI). For example, the standard run type variable is also set here: https://github.com/snoplus/orca/blob/6d59fa7575ff02f734d759db6d5c0d6654e2cef0/Source/Experiments/SNOP/SNOPModel.m#L2397. So, if for whatever reason some piece of code called `startStandardRun` in the middle of a run starting, it would display the wrong value. In addition, it's a bit of future proofing in case the standard run variable gets set from code somewhere else (I think there are various parts of the ELLIE code that automatically start runs without the user directly hitting the Start button).

Since this change is orthogonal to the issue above, though I'm happy to merge this since it will probably cover most of the cases. Let me know if you want to go ahead, and if so, I can merge after it's been tested.

**Comment by jcaravaca** [comment]
Tested OK at the TS.

**Comment by tlatorre-uchicago** [comment]
merged.

**Pull request closed without merging**
