### PR TITLE
SNO+: Change the SNOPDetector view to a webview

### PR DESCRIPTION
**Pull request by marzece**

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
Can you resubmit without changing the old SNO nib file?

**Comment by marzece** [comment]
Done

**Comment by tlatorre-uchicago** [comment]
There is still a function in the SNO+ model that posts a notification of type viewTypeChanged which is now no longer registered in the SNO+ controller. Can you verify that this was only used for the detector state tab and if so, delete that from the SNO+ model?

**Comment by marzece** [comment]
Yeah, you were talking about "ORSNOPModelViewTypeChanged" notification right? No thing else used that, so it's deleted now.

**Comment by tlatorre-uchicago** [comment]
merged.

**Pull request closed without merging**
