### PR TITLE
Add DIAGNOSTIC run

### PR DESCRIPTION
**Pull request by jcaravaca**
Same as Maintenance but without changing trigger settings

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
Can you comment on whether this was tested on the teststand?

**Comment by jcaravaca** [comment]
At the end it turned to be a bit more complicated: I need to make sure that all the GUIs are unlocked when in Diagnostic run. This implied some changed in the lock logic and changes in the controllers of ALL the SNO+ objects.
Tested OK at the teststand.

**Comment by jcaravaca** [comment]
I noticed that the Hardware Wizard will need to be changed as well but that'd mess up with core ORCA. I contacted Mark and he will implement a variable mask that can be defined by the individual experiments so that we can have Maintenance and Diagnostic runs to unlock the GUIs, since that's not in ORCA by design. I'll probably have to revisit the whole logic so hold the merge until I add then.

**Comment by jcaravaca** [comment]
Mark updated ORCA to allow unlock the Wizard using another mask. @tlatorre-uchicago could you resync with svn so that I can implement this?

**Comment by BenLand100** [comment]
@tlatorre-uchicago fyi I rebased from svn and pushed master

**Comment by jcaravaca** [comment]
Tested at the test stand. Treat runs with the 'DIAGNOSTIC' bit up as Maintenance but without changing the detector settings at the start of a run. This PR should be ready to go.

**Comment by tlatorre-uchicago** [comment]
I will test this out today during my shift and merge. Thanks!

**Comment by tlatorre-uchicago** [comment]
merged.

**Pull request closed without merging**
